ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "publicLocationLabel" TEXT;
ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "interests" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "onboardingStatus" TEXT NOT NULL DEFAULT 'NOT_STARTED';
ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "onboardingStep" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "onboardingCompletedAt" TIMESTAMP(3);
