import { useEffect, useMemo, useState, type ReactNode } from 'react'
import {
  Bell, Bookmark, BriefcaseBusiness, Building2, CheckCircle2, ChevronDown, CircleHelp,
  Flame, Heart, Home, Image, MapPin, Menu, MessageCircle, MoreHorizontal, Plus,
  Search, Send, ShieldAlert, ShoppingBag, Siren, Sparkles, ThumbsUp, TrafficCone, X,
  AlertTriangle, BadgeCheck, Car, Droplets, FlameKindling, Phone, Users, Wrench, Package, MessageSquare,
  Compass, UserRound, LayoutDashboard, Flag, Eye, Ban, ShieldCheck, BarChart3, FileWarning, Check, Trash2, ChevronRight
} from 'lucide-react'
import { NIGERIAN_STATES, PILOT } from './config/pilot'
import { LocationPicker } from './maps/LocationPicker'
import { WeatherCard } from './weather/WeatherCard'

type Category = 'General' | 'Question' | 'Safety' | 'Traffic' | 'Emergency' | 'Lost & Found' | 'Marketplace' | 'Services' | 'Events' | 'Jobs' | 'Local Issues'
type Post = { id: number; name: string; initials: string; tone: string; time: string; category: Category; text: string; reactions: number; comments: number; image?: string; verified?: boolean; location?: string; saved?: boolean }
type AlertStatus = 'Reported' | 'Community Confirmed' | 'Verified' | 'Resolved'
type Alert = { id: number; category: string; title: string; description: string; location: string; time: string; status: AlertStatus; confirmations: number; confidence: 'Low' | 'Developing' | 'High'; sourceType: 'Community report' | 'Official source' | 'Moderated report'; requiresReview?: boolean }
type Service = { id: number; name: string; category: string; description: string; area: string; phone: string; recommendations: number; verified?: boolean; image: string }
type Listing = { id: number; title: string; description: string; price: string; category: string; location: string; seller: string; initials: string; status: 'Available' | 'Reserved' | 'Sold'; image: string; time: string }
type Notification = { id: number; type: 'Comment' | 'Recommendation' | 'Announcement' | 'Safety alert' | 'Marketplace'; title: string; detail: string; time: string; unread?: boolean }

const categories: { name: Category; icon: typeof Home; color: string }[] = [
  { name: 'General', icon: Home, color: 'blue' }, { name: 'Question', icon: CircleHelp, color: 'violet' }, { name: 'Safety', icon: ShieldAlert, color: 'red' },
  { name: 'Traffic', icon: TrafficCone, color: 'amber' }, { name: 'Emergency', icon: Siren, color: 'red' },
  { name: 'Lost & Found', icon: CircleHelp, color: 'violet' }, { name: 'Marketplace', icon: ShoppingBag, color: 'green' },
  { name: 'Services', icon: Building2, color: 'orange' }, { name: 'Events', icon: Sparkles, color: 'pink' },
  { name: 'Jobs', icon: BriefcaseBusiness, color: 'cyan' }, { name: 'Local Issues', icon: Flame, color: 'yellow' }
]

const starterPosts: Post[] = []
const starterAlerts: Alert[] = []
const services: Service[] = []
const starterListings: Listing[] = []
const notifications: Notification[] = []
const apiBaseUrl = import.meta.env.VITE_API_BASE_URL ?? import.meta.env.VITE_API_URL ?? 'http://localhost:3000'
async function authRequest(path: string, init?: RequestInit) {
  const response = await fetch(`${apiBaseUrl}${path}`, { credentials: 'include', headers: { 'Content-Type': 'application/json', ...(init?.headers ?? {}) }, ...init })
  const payload = await response.json().catch(() => ({})) as { message?: string; error?: { message?: string }; emailVerified?: boolean }
  if (!response.ok) throw new Error(payload.error?.message ?? 'We could not complete that request. Please try again.')
  return payload
}

function Avatar({ initials, tone }: { initials: string; tone: string }) { return <div className={`avatar ${tone}`}>{initials}</div> }

export default function App() {
  const [posts, setPosts] = useState(starterPosts)
  const [activeCategory, setActiveCategory] = useState<Category | 'All'>('All')
  const [showComposer, setShowComposer] = useState(false)
  const [showAuth, setShowAuth] = useState(false)
  const [authMode, setAuthMode] = useState<'sign in' | 'join'>('join')
  const [communityOpen, setCommunityOpen] = useState(false)
  const [community, setCommunity] = useState<string>(PILOT.community)
  const [notice, setNotice] = useState('')
  const [view, setView] = useState<'home' | 'explore' | 'alerts' | 'services' | 'marketplace' | 'notifications' | 'admin' | 'profile' | 'community'>('home')
  const [showOnboarding, setShowOnboarding] = useState(false)
  const [userName, setUserName] = useState('Neighbour')
  const [searchTerm, setSearchTerm] = useState('')
  const [authDeepLink, setAuthDeepLink] = useState<{ type: 'verify' | 'reset'; token: string } | undefined>()
  const unreadNotificationCount = notifications.filter(notification => notification.unread).length

  useEffect(() => {
    const token = new URLSearchParams(window.location.search).get('token')
    const type = window.location.pathname === '/verify-email' ? 'verify' : window.location.pathname === '/reset-password' ? 'reset' : undefined
    if (type && token) { setAuthDeepLink({ type, token }); setShowAuth(true); setAuthMode(type === 'reset' ? 'sign in' : 'join') }
  }, [])

  const displayedPosts = useMemo(() => activeCategory === 'All' ? posts : posts.filter(p => p.category === activeCategory), [posts, activeCategory])
  const publish = (text: string, category: Category) => {
    setPosts([{ id: Date.now(), name: userName, initials: userName.slice(0, 2).toUpperCase(), tone: 'navy', time: 'Just now', category, text, reactions: 0, comments: 0, location: community }, ...posts])
    setShowComposer(false); setNotice(`Your update is now live in ${community}.`)
    window.setTimeout(() => setNotice(''), 3500)
  }
  return <div className="app-shell">
    <header className="topbar">
      <a className="brand" href="#top" aria-label="Around Me home"><span className="brand-mark"><MapPin size={22}/></span><span>Around<span>Me</span></span></a>
      <button className="community-switcher" onClick={() => setCommunityOpen(!communityOpen)}><MapPin size={17}/><span>{community}, Ojo</span><ChevronDown size={16}/></button>
      {communityOpen && <div className="community-menu"><b>Ojo pilot communities</b>{PILOT.areas.slice(0, 5).map(area => <button key={area} onClick={() => {setCommunity(area);setCommunityOpen(false)}}>{area === community ? '✓ ' : ''}{area}</button>)}<button className="add-community" onClick={() => setShowOnboarding(true)}><Plus size={15}/> Find an Ojo area</button></div>}
      <label className="search"><Search size={18}/><input value={searchTerm} onChange={e => setSearchTerm(e.target.value)} placeholder="Search communities, posts, services..."/></label>
      <div className="top-actions"><button className="icon-button" onClick={() => setView('notifications')} aria-label={unreadNotificationCount ? `${unreadNotificationCount} unread notifications` : 'Notifications'}><Bell size={20}/>{unreadNotificationCount > 0 && <i>{unreadNotificationCount}</i>}</button><button className="login" onClick={() => {setAuthMode('sign in');setShowAuth(true)}}>Sign in</button><button className="join" onClick={() => {setAuthMode('join');setShowAuth(true)}}>Join your community</button><button className="mobile-menu"><Menu/></button></div>
    </header>

    <main id="top" className="layout">
      <aside className="left-rail">
        <nav><a className={view === 'home' ? 'selected' : ''} onClick={() => setView('home')}><Home size={20}/> Home</a><a className={view === 'explore' ? 'selected' : ''} onClick={() => setView('explore')}><Compass size={20}/> Explore</a><a className={view === 'alerts' ? 'selected' : ''} onClick={() => setView('alerts')}><Siren size={20}/> Alerts <span className="nav-count">{starterAlerts.filter(a => a.status !== 'Resolved').length}</span></a><a className={view === 'marketplace' ? 'selected' : ''} onClick={() => setView('marketplace')}><ShoppingBag size={20}/> Marketplace</a><a className={view === 'services' ? 'selected' : ''} onClick={() => setView('services')}><Wrench size={20}/> Services</a><a className={view === 'profile' ? 'selected' : ''} onClick={() => setView('profile')}><UserRound size={20}/> Profile</a></nav>
        <div className="rail-section"><p className="eyebrow">YOUR COMMUNITY</p><a className="community-link"><span className="community-icon">L1</span>{community}</a><button className="text-button"><Plus size={17}/> Join another community</button></div>
        <div className="rail-footer"><a>About Around Me</a><a>Guidelines</a><a>Help centre</a><a className="admin-link" onClick={() => setView('admin')}><LayoutDashboard size={14}/> Admin dashboard</a><p>© 2026 Around Me</p></div>
      </aside>

      <section className="feed">
        {view === 'home' ? <>
        <div className="demo-notice"><Sparkles size={15}/><span>Ojo pilot preview. Live activity will appear only after the database and API are connected.</span></div>
        <div className="feed-heading"><div><p className="eyebrow">OJO PILOT · NEIGHBOURHOOD FEED</p><h1>What’s happening around Ojo?</h1><p><MapPin size={14}/> {community} · {PILOT.lga}, {PILOT.state}</p></div><button className="create-button" onClick={() => setShowComposer(true)}><Plus size={19}/> Create post</button></div>
        <AroundMeNow posts={posts} community={community} onNavigate={setView}/>
        <div className="category-row"><button className={activeCategory === 'All' ? 'chip active' : 'chip'} onClick={() => setActiveCategory('All')}>For you</button>{categories.slice(0, 5).map(c => <button key={c.name} className={activeCategory === c.name ? 'chip active' : 'chip'} onClick={() => setActiveCategory(c.name)}>{c.name}</button>)}<button className="chip">More <ChevronDown size={14}/></button></div>
        {showComposer && <Composer onClose={() => setShowComposer(false)} onPublish={publish}/>} 
        <button className="quick-post" onClick={() => setShowComposer(true)}><Avatar initials="OA" tone="navy"/><span>Share something with your neighbours...</span><Image size={21}/></button>
        {displayedPosts.map(post => <PostCard key={post.id} post={post} />)}
        {displayedPosts.length === 0 && <div className="empty"><Sparkles/><h3>No {activeCategory} posts yet</h3><p>Be the first neighbour to share an update.</p><button className="join" onClick={() => setShowComposer(true)}>Create a post</button></div>}
        </> : view === 'alerts' ? <AlertsPage community={community} setNotice={setNotice}/> : view === 'services' ? <ServicesPage community={community} setNotice={setNotice}/> : view === 'marketplace' ? <MarketplacePage community={community} setNotice={setNotice}/> : view === 'notifications' ? <NotificationsPage/> : view === 'explore' ? <ExplorePage community={community} onNavigate={setView} searchTerm={searchTerm}/> : view === 'profile' ? <ProfilePage userName={userName} community={community} onCommunityChange={setCommunity} posts={posts} onOnboard={() => setShowOnboarding(true)}/> : view === 'community' ? <CommunityProfile community={community} posts={posts} onBack={() => setView('home')}/> : <AdminDashboard setNotice={setNotice}/>} 
      </section>

      <aside className="right-rail">
        <section className="card weather"><WeatherCard location={community}/><button aria-label="Weather options"><MoreHorizontal size={18}/></button></section>
        <section className="card welcome"><div className="welcome-illustration"><span>🏠</span><span>🌿</span></div><h2>Your neighbourhood,<br/>made friendlier.</h2><p>Connect with people and places that make your local life better.</p><button className="join" onClick={() => {setAuthMode('join');setShowAuth(true)}}>Join Around Me</button></section>
        <section className="card trending"><div className="section-title"><h3>Ojo launch board</h3><button onClick={() => setShowComposer(true)}>Share update</button></div><a><span className="topic-dot orange-dot"/>Power reports <small>No reports yet</small></a><a><span className="topic-dot green-dot"/>Traffic & roads <small>No reports yet</small></a><a><span className="topic-dot red-dot"/>Local services <small>Be first to recommend</small></a></section>
        <section className="safety-note"><ShieldAlert size={18}/><p><b>Your location stays private.</b> We only show the community you choose—not your exact address.</p></section>
      </aside>
    </main>
    <nav className="mobile-bottom" aria-label="Mobile navigation"><button className={view === 'home' ? 'active' : ''} onClick={() => setView('home')}><Home/><span>Home</span></button><button className={view === 'explore' ? 'active' : ''} onClick={() => setView('explore')}><Compass/><span>Explore</span></button><button className="mobile-post" onClick={() => setShowComposer(true)}><Plus/><span>Post</span></button><button className={view === 'alerts' ? 'active' : ''} onClick={() => setView('alerts')}><Siren/><span>Alerts</span></button><button className={view === 'profile' ? 'active' : ''} onClick={() => setView('profile')}><UserRound/><span>Profile</span></button></nav>
    {notice && <div className="toast"><CheckCircle2 size={19}/>{notice}</div>}
    {showAuth && <AuthModal mode={authMode} deepLink={authDeepLink} close={() => {setShowAuth(false);setAuthDeepLink(undefined)}} onModeChange={setAuthMode} onJoinPreview={() => {setShowAuth(false);setShowOnboarding(true)}} />}
    {showOnboarding && <LocationOnboarding close={() => setShowOnboarding(false)} complete={({ name, primaryCommunity }) => {setUserName(name || 'Neighbour');setCommunity(primaryCommunity);setShowOnboarding(false);setView('home');setNotice(`Your primary community is now ${primaryCommunity}.`)}} />}
  </div>
}

function AroundMeNow({ posts, community, onNavigate }: { posts: Post[]; community: string; onNavigate: (view: 'alerts' | 'marketplace' | 'services') => void }) {
  const alertCount = starterAlerts.filter(alert => alert.status !== 'Resolved').length
  return <section className="now-panel"><div className="section-title"><div><p className="eyebrow">AROUND ME NOW · OJO</p><h2>From your community</h2></div><span>Platform activity only</span></div><div className="now-grid"><button onClick={() => onNavigate('alerts')}><Siren/><b>{alertCount ? `${alertCount} community reports` : 'No alerts right now'}</b><small>Reports appear after submission</small></button><button onClick={() => onNavigate('marketplace')}><ShoppingBag/><b>{starterListings.length ? `${starterListings.length} local listings` : 'List an item near Ojo'}</b><small>Shared by neighbours</small></button><button onClick={() => onNavigate('services')}><Wrench/><b>Recommend a local service</b><small>Services near {community}</small></button></div></section>
}

function LocationOnboarding({ close, complete }: { close: () => void; complete: (value: { name: string; primaryCommunity: string }) => void }) {
  const [step, setStep] = useState(1); const [name, setName] = useState(''); const [state, setState] = useState<string>(PILOT.state); const [lga, setLga] = useState<string>(PILOT.lga); const [area, setArea] = useState<string>(PILOT.community)
  const isOjoPilot = state === PILOT.state && lga === PILOT.lga
  return <div className="modal-backdrop" role="dialog" aria-modal="true"><section className="onboarding-modal"><button className="modal-close" onClick={close}><X/></button><div className="onboarding-progress"><i className={step >= 1 ? 'done' : ''}/><i className={step >= 2 ? 'done' : ''}/><i className={step >= 3 ? 'done' : ''}/></div>{step === 1 ? <><p className="eyebrow">WELCOME TO AROUND ME{state === PILOT.state ? ' · OJO PILOT' : ''}</p><h2>Start with your community</h2><p>Available across Nigeria. We’ll show your chosen area—not your exact home address.</p><label>Your name<input value={name} onChange={e => setName(e.target.value)} placeholder="What should neighbours call you?"/></label><button className="join wide" disabled={!name.trim()} onClick={() => setStep(2)}>Continue</button></> : step === 2 ? <><p className="eyebrow">LOCATION</p><h2>Where are you based?</h2><p>Select a state and LGA. Ojo has expanded pilot area choices; more verified LGAs will be imported over time.</p><label>State<input list="nigerian-states" value={state} onChange={e => {setState(e.target.value); setLga(e.target.value === PILOT.state ? PILOT.lga : ''); setArea('')}}/><datalist id="nigerian-states">{NIGERIAN_STATES.map(value => <option key={value} value={value}/>)}</datalist></label><label>Local government area<input list={state === PILOT.state ? 'lagos-lgas' : undefined} value={lga} onChange={e => setLga(e.target.value)} placeholder="Search or enter your LGA"/>{state === PILOT.state && <datalist id="lagos-lgas"><option value={PILOT.lga}/></datalist>}</label><button className="join wide" disabled={!state || !lga} onClick={() => setStep(3)}>Continue</button><button className="link-button" onClick={() => setStep(1)}>Back</button></> : <><p className="eyebrow">YOUR PRIMARY AREA</p><h2>{isOjoPilot ? 'Where in Ojo are you?' : 'Choose your local area'}</h2><p>{isOjoPilot ? 'Popular Ojo areas are available first. You can follow nearby communities later.' : 'Use a recognised local area name. Exact residential addresses are never requested.'}</p><label>Area<input list={isOjoPilot ? 'ojo-areas' : undefined} value={area} onChange={e => setArea(e.target.value)} placeholder="Search area or neighbourhood"/>{isOjoPilot && <datalist id="ojo-areas">{PILOT.areas.map(value => <option key={value} value={value}/>)}</datalist>}</label><LocationPicker onSelect={location => { setArea(location.neighbourhood ?? location.city ?? location.town ?? location.district ?? location.state ?? area); setState(location.state ?? state); setLga(location.lga ?? lga) }}/><button className="join wide" disabled={!area} onClick={() => complete({name, primaryCommunity: area})}>Join {area}</button><button className="link-button" onClick={() => setStep(2)}>Back</button></>}</section></div>
}

function ExplorePage({ community, onNavigate, searchTerm }: { community: string; onNavigate: (view: 'community' | 'services' | 'marketplace' | 'alerts') => void; searchTerm: string }) {
  const results = [
    { type: 'Community', title: community, detail: 'Your primary neighbourhood', action: 'community' as const },
    { type: 'Service', title: 'Recommend a local provider', detail: 'Be the first Ojo resident to recommend a service.', action: 'services' as const },
    { type: 'Marketplace', title: 'List something for sale', detail: `Marketplace · ${PILOT.lga}`, action: 'marketplace' as const },
    { type: 'Alert', title: 'Community reports', detail: 'Review source types and confirmations', action: 'alerts' as const }
  ].filter(result => !searchTerm || `${result.type} ${result.title} ${result.detail}`.toLowerCase().includes(searchTerm.toLowerCase()))
  return <div className="directory-page"><div className="page-hero explore-hero"><div><p className="eyebrow">DISCOVER AROUND YOU</p><h1>Explore nearby</h1><p>Communities, trusted local help, marketplace items, and resident-submitted updates.</p></div><Compass size={36}/></div><div className="explore-section"><h2>Search results {searchTerm && <small>for “{searchTerm}”</small>}</h2>{results.map(result => <button className="explore-result card" key={result.title} onClick={() => onNavigate(result.action)}><span>{result.type}</span><div><b>{result.title}</b><p>{result.detail}</p></div><ChevronRight size={18}/></button>)}{results.length === 0 && <div className="empty"><Search/><h3>No nearby matches</h3><p>Try another community, service or item name.</p></div>}</div></div>
}

function ProfilePage({ userName, community, onCommunityChange, posts, onOnboard }: { userName: string; community: string; onCommunityChange: (value: string) => void; posts: Post[]; onOnboard: () => void }) {
  const [editing, setEditing] = useState(false); const [choice, setChoice] = useState(community)
  return <div className="directory-page"><section className="profile-hero"><Avatar initials={userName.slice(0,2).toUpperCase()} tone="navy"/><div><p className="eyebrow">YOUR PROFILE</p><h1>{userName}</h1><p><MapPin size={14}/>{community} · {PILOT.lga}</p><span className="profile-status">Community profile setup pending verification</span></div><button className="login" onClick={() => setEditing(!editing)}>Settings</button></section>{editing && <section className="profile-settings card"><h2>Primary Ojo area</h2><p>Your selected area is visible; your exact address remains private.</p><input list="profile-communities" value={choice} onChange={e => setChoice(e.target.value)}/><datalist id="profile-communities">{PILOT.areas.map(area => <option key={area} value={area}/>)}</datalist><button className="join" onClick={() => {onCommunityChange(choice);setEditing(false)}}>Save primary area</button><button className="link-button" onClick={onOnboard}>Update location details</button></section>}<div className="profile-stats"><div><b>{posts.filter(post => post.name === userName).length}</b><span>Posts</span></div><div><b>0</b><span>Recommendations</span></div><div><b>0</b><span>Listings</span></div></div><section className="profile-section"><h2>Your activity</h2><p>Posts, recommendations and marketplace listings you share will appear here. Private contact and exact location information are never shown publicly.</p></section></div>
}

function CommunityProfile({ community, posts, onBack }: { community: string; posts: Post[]; onBack: () => void }) { return <div className="directory-page"><button className="back-button" onClick={onBack}>← Back to home</button><section className="community-hero"><span className="community-icon">{community.slice(0,2).toUpperCase()}</span><div><p className="eyebrow">COMMUNITY PROFILE</p><h1>{community}</h1><p>Neighbourhood updates, local help, and community-reported information.</p><small>Member count and community admins will appear once connected to live membership data.</small></div><button className="join">Joined</button></section><div className="community-tabs"><span>Posts ({posts.length})</span><span>Alerts (platform data)</span><span>Businesses</span><span>Marketplace</span></div><div className="community-posts">{posts.slice(0, 2).map(post => <PostCard key={post.id} post={post}/>)}</div></div> }

function AlertsPage({ community, setNotice }: { community: string; setNotice: (value: string) => void }) {
  const [alerts, setAlerts] = useState(starterAlerts)
  const [showReport, setShowReport] = useState(false)
  const [filter, setFilter] = useState<'Active' | 'All'>('Active')
  const [selectedAlert, setSelectedAlert] = useState<Alert | null>(null)
  const visible = filter === 'All' ? alerts : alerts.filter(alert => alert.status !== 'Resolved')
  const confirm = (id: number) => setAlerts(alerts.map(alert => alert.id === id ? { ...alert, confirmations: alert.confirmations + 1, status: alert.confirmations >= 4 && alert.status === 'Reported' ? 'Community Confirmed' : alert.status } : alert))
  const submit = (alert: Omit<Alert, 'id' | 'time' | 'status' | 'confirmations' | 'confidence' | 'sourceType'>) => { setAlerts([{ ...alert, id: Date.now(), time: 'Just now', status: 'Reported', confirmations: 1, confidence: 'Low', sourceType: 'Community report', requiresReview: /Crime|Fire|Missing/.test(alert.category) }, ...alerts]); setShowReport(false); setNotice('Your alert is published as a community report—not a verified fact.'); window.setTimeout(() => setNotice(''), 4500) }
  return <div className="directory-page">{selectedAlert ? <AlertDetail alert={selectedAlert} close={() => setSelectedAlert(null)}/> : <><div className="page-hero alert-hero"><div><p className="eyebrow">OJO COMMUNITY SAFETY</p><h1>Alerts near you</h1><p>Stay informed by neighbours. Reports are not verified facts unless their status says so.</p></div><button className="urgent-button" onClick={() => setShowReport(true)}><AlertTriangle size={18}/> Report an incident</button></div><div className="alert-guidance"><ShieldAlert size={19}/><div><b>For immediate danger, contact emergency services first.</b><span>Share an approximate area only. Never post an exact home address or personal information.</span></div></div><p className="intelligence-disclaimer">No external intelligence source is currently connected. Ojo alerts shown here come from real platform records once the database is connected.</p><div className="filter-line"><div><button className={filter === 'Active' ? 'chip active' : 'chip'} onClick={() => setFilter('Active')}>Active alerts</button><button className={filter === 'All' ? 'chip active' : 'chip'} onClick={() => setFilter('All')}>All reports</button></div><span>{visible.length} in {community}</span></div>{showReport && <AlertComposer close={() => setShowReport(false)} submit={submit}/>}<div className="alerts-list">{visible.map(alert => <AlertCard key={alert.id} alert={alert} onConfirm={() => confirm(alert.id)} onDetail={() => setSelectedAlert(alert)}/>)}</div>{visible.length === 0 && <div className="empty"><Siren/><h3>No traffic or safety reports in Ojo right now</h3><p>Know what is happening nearby? Share a good-faith community report.</p></div>}</>}</div>
}

function AlertCard({ alert, onConfirm, onDetail }: { alert: Alert; onConfirm: () => void; onDetail: () => void }) {
  const [confirmed, setConfirmed] = useState(false); const [flagged, setFlagged] = useState(false); const [auditOpen, setAuditOpen] = useState(false)
  const icon = alert.category === 'Flooding' ? Droplets : alert.category === 'Road closure' ? Car : alert.category === 'Security' ? ShieldAlert : FlameKindling
  const Icon = icon
  return <article className="alert-card card"><div className="alert-card-top"><div className="alert-icon"><Icon size={20}/></div><div className="alert-main"><div className="alert-meta"><span>{alert.category}</span><span>•</span><span>{alert.time}</span><span>•</span><span>{alert.sourceType}</span></div><h2>{alert.title}</h2><p>{alert.description}</p></div></div>{alert.requiresReview && <div className="review-gate"><ShieldCheck size={14}/> High-risk report: held from broad alerts pending moderator or authoritative-source review.</div>}<div className="alert-location"><MapPin size={15}/>{alert.location}</div><div className="alert-footer"><div><span className={`status-pill ${alert.status.toLowerCase().replaceAll(' ', '-')}`}>{alert.status}</span><span className={`confidence ${alert.confidence.toLowerCase()}`}>{alert.confidence} confidence</span></div><button className={confirmed ? 'confirm-button confirmed' : 'confirm-button'} onClick={() => {if (!confirmed) onConfirm(); setConfirmed(!confirmed)}}><Users size={15}/>{confirmed ? 'Confirmed' : `Confirm (${alert.confirmations})`}</button></div><div className="alert-safety-actions"><button onClick={onDetail}><ChevronRight size={14}/> Details</button><button onClick={() => setAuditOpen(!auditOpen)}><Eye size={14}/> Alert history</button><button className={flagged ? 'flagged' : ''} onClick={() => setFlagged(true)}><Flag size={14}/>{flagged ? 'Flag submitted' : 'Report misinformation'}</button></div>{auditOpen && <div className="audit-trail"><b>Audit trail</b><span>{alert.time} · {alert.sourceType} received</span><span>{alert.confirmations} community confirmations recorded</span><span>Moderation state: {alert.requiresReview ? 'Review required before mass notification' : 'Standard review policy'}</span></div>}</article>
}

function AlertDetail({ alert, close }: { alert: Alert; close: () => void }) { return <div className="alert-detail"><button className="back-button" onClick={close}>← Back to alerts</button><section className="alert-detail-hero"><p className="eyebrow">{alert.sourceType.toUpperCase()}</p><h1>{alert.title}</h1><p>{alert.description}</p><div><span className={`status-pill ${alert.status.toLowerCase().replaceAll(' ', '-')}`}>{alert.status}</span><span className={`confidence ${alert.confidence.toLowerCase()}`}>{alert.confidence} confidence</span></div></section><div className="detail-grid"><section className="card detail-section"><h2>Approximate location</h2><div className="approximate-map"><MapPin size={25}/><span>{alert.location}</span><small>Map detail is intentionally approximate to protect neighbours’ privacy.</small></div><h2>Timeline</h2><ol className="alert-timeline"><li><b>{alert.time}</b><span>Incident reported as a {alert.sourceType.toLowerCase()}.</span></li><li><b>After report</b><span>{alert.confirmations} community confirmations recorded.</span></li><li><b>Current</b><span>Status is {alert.status}; confidence is {alert.confidence.toLowerCase()}.</span></li></ol></section><aside className="card detail-section"><h2>Sources & updates</h2><p><b>Source type:</b> {alert.sourceType}</p><p><b>Community confirmations:</b> {alert.confirmations}</p><p><b>Additional external sources:</b> None connected in this MVP.</p><button className="confirm-button"><Users size={15}/> I can confirm this</button><button className="detail-flag"><Flag size={14}/> This information is incorrect</button></aside></div><section className="card detail-section"><h2>Community comments</h2><p className="muted">Comments will load here when connected to the alert API. This demo does not invent resident updates.</p></section></div> }

function AlertComposer({ close, submit }: { close: () => void; submit: (alert: Omit<Alert, 'id' | 'time' | 'status' | 'confirmations' | 'confidence' | 'sourceType'>) => void }) {
  const [category, setCategory] = useState('Other urgent incident'); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [location, setLocation] = useState('')
  return <section className="alert-composer card"><div className="composer-head"><div><h2>Report a local incident</h2><p>Your report will begin with <b>Reported</b> status.</p></div><button onClick={close}><X/></button></div><div className="report-grid"><label>Category<select value={category} onChange={e => setCategory(e.target.value)}>{['Crime / security', 'Accident', 'Fire', 'Flooding', 'Missing person', 'Road closure', 'Dangerous area', 'Other urgent incident'].map(item => <option key={item}>{item}</option>)}</select></label><label>Approximate location<input value={location} onChange={e => setLocation(e.target.value)} placeholder="e.g. near Iba or Alaba"/></label></div><label>Short title<input value={title} onChange={e => setTitle(e.target.value)} placeholder="What happened?"/></label><label>Description<textarea value={description} onChange={e => setDescription(e.target.value)} placeholder="Share only what you know. Avoid names, exact addresses and speculation."/></label><div className="composer-footer"><small>By posting, you confirm this is a good-faith community report.</small><button className="urgent-button" disabled={!title.trim() || !description.trim() || !location.trim()} onClick={() => submit({ category, title, description, location })}>Publish report</button></div></section>
}

function ServicesPage({ community, setNotice }: { community: string; setNotice: (value: string) => void }) {
  const [query, setQuery] = useState(''); const [serviceCategory, setServiceCategory] = useState('All services'); const [recommendations, setRecommendations] = useState<Record<number, boolean>>({})
  const allCategories = ['All services', 'Electricians', 'Plumbers', 'Mechanics', 'Cleaners', 'AC technicians', 'Carpenters', 'Security', 'Food', 'Hair / beauty', 'Tailors', 'Moving services']
  const results = services.filter(service => (serviceCategory === 'All services' || service.category.toLowerCase().includes(serviceCategory.replace('s', '').toLowerCase())) && `${service.name} ${service.category}`.toLowerCase().includes(query.toLowerCase()))
  const recommend = (id: number) => { setRecommendations({...recommendations, [id]: !recommendations[id]}); setNotice(recommendations[id] ? 'Recommendation removed.' : 'Thanks for strengthening a trusted local recommendation.'); window.setTimeout(() => setNotice(''), 3200) }
  return <div className="directory-page"><div className="page-hero services-hero"><div><p className="eyebrow">TRUSTED AROUND YOU</p><h1>Local services</h1><p>Find providers your neighbours have used around {community}.</p></div><div className="services-badge"><Users size={21}/><b>Community-led</b><span>Recommendations over ads</span></div></div><div className="service-search"><Search size={19}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search electricians, cleaners, tailors..."/><select value={serviceCategory} onChange={e => setServiceCategory(e.target.value)}>{allCategories.map(category => <option key={category}>{category}</option>)}</select></div><div className="recommendation-callout"><div className="rec-icon"><ThumbsUp size={20}/></div><div><b>Need a recommendation?</b><p>Ask your community who they’ve personally used—community trust matters more than a star rating.</p></div><button onClick={() => setNotice('Your recommendation request has been added to the community feed.')}>Ask neighbours</button></div><div className="directory-heading"><h2>Recommended in {community}</h2><span>{results.length} providers</span></div><div className="service-grid">{results.map(service => <article className="service-card card" key={service.id}><div className="service-cover"><span>{service.image}</span><span className="service-category">{service.category}</span></div><div className="service-content"><div className="service-name"><h3>{service.name}</h3>{service.verified && <span title="Verified provider"><BadgeCheck size={17}/></span>}</div><p>{service.description}</p><div className="service-details"><span><MapPin size={14}/>{service.area}</span><span><Phone size={14}/>{service.phone}</span></div><div className="service-actions"><button className={recommendations[service.id] ? 'recommend active-recommend' : 'recommend'} onClick={() => recommend(service.id)}><ThumbsUp size={15}/>{recommendations[service.id] ? 'Recommended' : 'Recommend'} <b>{service.recommendations + (recommendations[service.id] ? 1 : 0)}</b></button><button className="view-provider">View profile</button></div></div></article>)}</div>{results.length === 0 && <div className="empty"><Wrench/><h3>No providers found</h3><p>Try another service category or ask your neighbours.</p></div>}</div>
}

function MarketplacePage({ community, setNotice }: { community: string; setNotice: (value: string) => void }) {
  const [listings, setListings] = useState(starterListings); const [query, setQuery] = useState(''); const [category, setCategory] = useState('All categories'); const [showListing, setShowListing] = useState(false)
  const filtered = listings.filter(listing => (category === 'All categories' || listing.category === category) && `${listing.title} ${listing.description}`.toLowerCase().includes(query.toLowerCase()))
  const publish = (listing: Omit<Listing, 'id' | 'time' | 'status' | 'seller' | 'initials' | 'image'>) => { setListings([{...listing, id: Date.now(), time: 'Just now', status: 'Available', seller: 'You', initials: 'YO', image: '📦'}, ...listings]); setShowListing(false); setNotice('Your local listing is live. Your exact address is not shown.'); window.setTimeout(() => setNotice(''), 3500) }
  return <div className="directory-page"><div className="page-hero marketplace-hero"><div><p className="eyebrow">BUY & SELL CLOSE TO HOME</p><h1>Marketplace</h1><p>Find useful things from neighbours around {community}.</p></div><button className="create-button" onClick={() => setShowListing(true)}><Plus size={18}/> Create listing</button></div><div className="marketplace-note"><ShieldAlert size={18}/><span><b>Keep it local and safe.</b> Arrange exchanges in public places and use in-app messaging before sharing phone numbers.</span></div><div className="service-search marketplace-search"><Search size={19}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search local listings"/><select value={category} onChange={e => setCategory(e.target.value)}>{['All categories', 'Electronics', 'Cars', 'Phones', 'Furniture', 'Clothing', 'Food', 'Services', 'Other'].map(item => <option key={item}>{item}</option>)}</select></div>{showListing && <ListingComposer close={() => setShowListing(false)} publish={publish}/>}<div className="directory-heading"><h2>Nearby listings</h2><span>{filtered.length} available near you</span></div><div className="listing-grid">{filtered.map(listing => <ListingCard key={listing.id} listing={listing} setNotice={setNotice}/>)}</div>{filtered.length === 0 && <div className="empty"><Package/><h3>No listings found</h3><p>Try another category or create a local listing.</p></div>}</div>
}

function ListingCard({ listing, setNotice }: { listing: Listing; setNotice: (notice: string) => void }) {
  const [saved, setSaved] = useState(false)
  return <article className="listing-card card"><div className="listing-image"><span>{listing.image}</span><span className={`listing-status ${listing.status.toLowerCase()}`}>{listing.status}</span><button className={saved ? 'listing-save saved' : 'listing-save'} onClick={() => setSaved(!saved)} aria-label="Save listing"><Bookmark size={16} fill={saved ? 'currentColor' : 'none'}/></button></div><div className="listing-content"><p className="listing-category">{listing.category}</p><h3>{listing.title}</h3><h2>{listing.price}</h2><p>{listing.description}</p><div className="listing-location"><MapPin size={13}/>{listing.location} · {listing.time}</div><div className="seller-row"><Avatar initials={listing.initials} tone="navy"/><span><b>{listing.seller}</b><small>Neighbour seller</small></span><button onClick={() => setNotice('Messaging will be available once secure account messaging is connected.') }><MessageSquare size={15}/> Message</button></div></div></article>
}

function ListingComposer({ close, publish }: { close: () => void; publish: (listing: Omit<Listing, 'id' | 'time' | 'status' | 'seller' | 'initials' | 'image'>) => void }) {
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [price, setPrice] = useState(''); const [category, setCategory] = useState('Other'); const [location, setLocation] = useState('')
  return <section className="alert-composer card listing-composer"><div className="composer-head"><div><h2>Create a local listing</h2><p>Use an approximate pickup area—never your home address.</p></div><button onClick={close}><X/></button></div><div className="report-grid"><label>Listing title<input value={title} onChange={e => setTitle(e.target.value)} placeholder="e.g. iPhone 13, 128GB"/></label><label>Price<input value={price} onChange={e => setPrice(e.target.value)} placeholder="e.g. ₦250,000"/></label><label>Category<select value={category} onChange={e => setCategory(e.target.value)}>{['Electronics', 'Cars', 'Phones', 'Furniture', 'Clothing', 'Food', 'Services', 'Other'].map(item => <option key={item}>{item}</option>)}</select></label><label>Approximate location<input value={location} onChange={e => setLocation(e.target.value)} placeholder="e.g. Ojo, Iba, or Alaba"/></label></div><label>Description<textarea value={description} onChange={e => setDescription(e.target.value)} placeholder="Condition, features, and any useful details"/></label><div className="composer-footer"><small>Image uploads are prepared for the connected storage service.</small><button className="create-button" disabled={!title || !description || !price || !location} onClick={() => publish({title, description, price, category, location})}>Publish listing</button></div></section>
}

function NotificationsPage() {
  const [items, setItems] = useState(notifications); const [preferencesOpen, setPreferencesOpen] = useState(false)
  return <div className="directory-page"><div className="page-hero notifications-hero"><div><p className="eyebrow">YOUR UPDATES</p><h1>Notifications</h1><p>Comments, community updates, local activity and safety alerts in one place.</p></div><button className="login" onClick={() => setPreferencesOpen(!preferencesOpen)}>Notification settings</button></div>{preferencesOpen && <section className="preferences card"><h3>Notification preferences</h3><p>Security notices remain enabled for account safety. Push delivery is prepared but not yet connected.</p>{['Replies and comments', 'Mentions', 'Local alerts', 'Event reminders', 'Community updates', 'Product updates'].map((item, index) => <label key={item}><input type="checkbox" defaultChecked={index !== 5}/>{item}<span>Enabled</span></label>)}</section>}<div className="notification-actions"><h2>Recent</h2><button onClick={() => setItems(items.map(item => ({...item, unread: false})))}>Mark all as read</button></div>{items.length === 0 ? <div className="empty"><Bell/><h3>You’re all caught up</h3><p>New replies, local updates and account notices will appear here.</p></div> : <div className="notifications-list">{items.map(item => <article className={item.unread ? 'notification card unread' : 'notification card'} onClick={() => setItems(items.map(current => current.id === item.id ? {...current, unread: false} : current))} key={item.id}><div className={`notification-icon ${item.type.toLowerCase().replaceAll(' ', '-')}`}>{item.type === 'Safety alert' ? <Siren size={18}/> : item.type === 'Marketplace' ? <ShoppingBag size={18}/> : item.type === 'Comment' ? <MessageCircle size={18}/> : item.type === 'Recommendation' ? <ThumbsUp size={18}/> : <Bell size={18}/>}</div><div><h3>{item.title}</h3><p>{item.detail}</p><span>{item.time}</span></div>{item.unread && <i/>}</article>)}</div>}</div>
}

function AdminDashboard({ setNotice }: { setNotice: (value: string) => void }) {
  const [section, setSection] = useState('Overview'); const [reviewed, setReviewed] = useState<Record<string, boolean>>({})
  const rows = section === 'Intelligence review' ? [['No external events are currently ingested', 'Source adapters disabled', 'Awaiting configuration']] : [['No live Ojo records yet', 'Connect the database-backed pilot API', 'Awaiting launch']]
  return <div className="admin-page"><div className="admin-hero"><div><p className="eyebrow">MODERATION WORKSPACE</p><h1>Around Me Admin</h1><p>Review community health without overstating what reports prove.</p></div><span><ShieldCheck size={18}/> Admin access</span></div><div className="admin-stats"><Stat icon={<Users/>} value="—" label="Live users" change="Backend required"/><Stat icon={<Building2/>} value="—" label="Live communities" change="Backend required"/><Stat icon={<Siren/>} value="—" label="Open alerts" change="No live source" warn/><Stat icon={<Flag/>} value="—" label="Content reports" change="No live source" warn/></div><div className="admin-layout"><aside className="admin-nav">{['Overview', 'Users', 'Communities', 'Posts', 'Reports', 'Alerts', 'Intelligence review', 'Businesses', 'Marketplace listings', 'Reported content', 'Verification requests', 'Analytics'].map(item => <button key={item} className={section === item ? 'active' : ''} onClick={() => setSection(item)}>{item}</button>)}</aside><section className="admin-content card"><div className="admin-content-head"><div><h2>{section}</h2><p>{section === 'Overview' ? 'Preview workspace; live operations need the backend API.' : 'Review, moderate and audit actions in this area.'}</p></div><button className="login" onClick={() => setNotice('Export is available when the backend reporting service is connected.')}>Export</button></div>{section === 'Overview' ? <AdminOverview setSection={setSection}/> : <div className="admin-table"><div className="admin-table-head"><span>Item</span><span>Context</span><span>Status</span><span>Action</span></div>{rows.map((row, index) => <div className="admin-row" key={row[0]}><span><b>{row[0]}</b><small>Preview record {index + 1}</small></span><span>{row[1]}</span><span><i className={row[2].includes('review') || row[2].includes('pending') || row[2].includes('Awaiting') ? 'needs-review' : ''}>{row[2]}</i></span><span>{reviewed[row[0]] ? <em>Reviewed</em> : <button onClick={() => {setReviewed({...reviewed, [row[0]]: true});setNotice(`${row[0]} marked reviewed in preview. Server audit storage is required for real actions.`)}}>Review <ChevronRight size={14}/></button>}</span></div>)}</div>}<div className="moderation-footer"><FileWarning size={16}/><span><b>Moderation hook:</b> removals, suspensions, verification and alert-resolution actions should create immutable audit events before changing public state.</span></div></section></div></div>
}

function AdminOverview({ setSection }: { setSection: (value: string) => void }) { return <><div className="review-queue"><div><h3>Priority review queue</h3><p>High-risk reports stay here until they have additional evidence or a moderator decision.</p></div><button className="urgent-button" onClick={() => setSection('Alerts')}>Review 2 alerts</button></div><div className="overview-grid"><article><BarChart3/><b>84%</b><span>Reports reviewed within 24 hours</span></article><article><ShieldCheck/><b>96%</b><span>Neighbour confirmations in good standing</span></article><article><BadgeCheck/><b>7</b><span>Business verification requests</span></article></div></> }
function Stat({ icon, value, label, change, warn }: { icon: ReactNode; value: string; label: string; change: string; warn?: boolean }) { return <article className={warn ? 'admin-stat warn' : 'admin-stat'}><div>{icon}</div><span><b>{value}</b><small>{label}</small></span><em>{change}</em></article> }

function PostCard({ post }: { post: Post }) {
  const [liked, setLiked] = useState(false); const [saved, setSaved] = useState(false); const [comments, setComments] = useState(post.comments); const [comment, setComment] = useState(''); const [reported, setReported] = useState(false)
  const meta = categories.find(c => c.name === post.category)!
  const Icon = meta.icon
  return <article className="post card"><div className="post-header"><Avatar initials={post.initials} tone={post.tone}/><div><div className="post-author">{post.name} {post.verified && <CheckCircle2 size={15} fill="currentColor"/>}</div><p>{post.time} · <MapPin size={13}/> {post.location || PILOT.community}</p></div><button className="more" onClick={() => setReported(!reported)} title="Report post"><MoreHorizontal size={20}/></button></div>{reported && <div className="report-box">Thanks—we’ve sent this post for review.</div>}<div className={`post-tag ${meta.color}`}><Icon size={14}/>{post.category}</div><p className="post-copy">{post.text}</p>{post.image && <img className="post-image" src={post.image} alt="Post attachment"/>}<div className="post-counts"><span>{liked ? post.reactions + 1 : post.reactions} reactions</span><span>{comments} comments</span></div><div className="post-actions"><button className={liked ? 'reacted' : ''} onClick={() => setLiked(!liked)}><Heart size={18} fill={liked ? 'currentColor' : 'none'}/> {liked ? 'Loved' : 'React'}</button><button onClick={() => document.getElementById(`comment-${post.id}`)?.focus()}><MessageCircle size={18}/> Comment</button><button className={saved ? 'reacted' : ''} onClick={() => setSaved(!saved)}><Bookmark size={18} fill={saved ? 'currentColor' : 'none'}/> {saved ? 'Saved' : 'Save'}</button></div><form className="comment-box" onSubmit={e => {e.preventDefault();if(comment.trim()){setComments(comments+1);setComment('')}}}><Avatar initials="OA" tone="navy"/><input id={`comment-${post.id}`} value={comment} onChange={e => setComment(e.target.value)} placeholder="Write a comment..."/><button aria-label="Send comment"><Send size={16}/></button></form></article>
}

function Composer({ onClose, onPublish }: { onClose: () => void; onPublish: (text: string, category: Category) => void }) {
  const [text, setText] = useState(''); const [category, setCategory] = useState<Category>('General'); const [location, setLocation] = useState<string>(PILOT.community)
  const urgent = category === 'Safety' || category === 'Traffic' || category === 'Emergency'
  return <section className="composer card"><div className="composer-head"><div><h2>Create a community post</h2><p>Share an approximate area only—your exact address will never be shown.</p></div><button onClick={onClose}><X/></button></div><div className="post-type-grid">{categories.filter(item => !['Services', 'Jobs'].includes(item.name)).map(item => <button key={item.name} className={category === item.name ? 'active' : ''} onClick={() => setCategory(item.name)}>{item.name}</button>)}</div>{urgent && <div className="post-safety-note"><ShieldAlert size={15}/><span>Urgent posts are community-submitted reports, not verified facts. Use the dedicated Alerts flow for incidents.</span></div>}<textarea autoFocus value={text} onChange={e => setText(e.target.value)} placeholder={category === 'Question' ? 'What would you like to ask your neighbours?' : 'What would you like to share with your neighbours?'}/><div className="composer-options"><label><MapPin size={15}/><input value={location} onChange={e => setLocation(e.target.value)} aria-label="Approximate location"/></label><span><Image size={15}/> Image upload connects to secure storage</span></div><div className="composer-footer"><select value={category} onChange={e => setCategory(e.target.value as Category)} aria-label="Post category">{categories.map(c => <option key={c.name}>{c.name}</option>)}</select><button className="join" disabled={!text.trim()} onClick={() => onPublish(`${text}${location ? `\n\nApproximate area: ${location}` : ''}`, category)}>Post to community</button></div></section>
}

function AuthModal({ mode, deepLink, close, onModeChange }: { mode: 'sign in' | 'join'; deepLink?: { type: 'verify' | 'reset'; token: string }; close: () => void; onModeChange: (mode: 'sign in' | 'join') => void; onJoinPreview: () => void }) {
  const [step, setStep] = useState<'form' | 'check-email' | 'forgot' | 'reset' | 'verified' | 'error'>(deepLink?.type === 'reset' ? 'reset' : 'form')
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { if (deepLink?.type === 'verify') { setBusy(true); authRequest(`/auth/verify-email?token=${encodeURIComponent(deepLink.token)}`).then(result => { setMessage(result.message ?? 'Your email has been verified.'); setStep('verified') }).catch(error => { setMessage(error.message); setStep('error') }).finally(() => setBusy(false)) } }, [deepLink])
  const submit = async () => { setBusy(true); setMessage(''); try {
    if (step === 'forgot') { const result = await authRequest('/auth/forgot-password', { method: 'POST', body: JSON.stringify({ email }) }); setMessage(result.message ?? 'Check your email.'); setStep('check-email') }
    else if (step === 'reset' && deepLink) { const result = await authRequest('/auth/reset-password', { method: 'POST', body: JSON.stringify({ token: deepLink.token, password }) }); setMessage(result.message ?? 'Your password has been reset.'); setStep('verified') }
    else if (mode === 'join') { const result = await authRequest('/auth/register', { method: 'POST', body: JSON.stringify({ displayName: name, email, password }) }); setMessage(result.message ?? 'Check your email to verify your account.'); setStep('check-email') }
    else { const result = await authRequest('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); setMessage(result.message ?? 'Signed in.'); if (result.emailVerified) close(); else setStep('check-email') }
  } catch (error) { setMessage(error instanceof Error ? error.message : 'We could not complete that request.'); setStep('error') } finally { setBusy(false) } }
  const resend = async () => { setBusy(true); try { const result = await authRequest('/auth/resend-verification', { method: 'POST', body: JSON.stringify({ email }) }); setMessage(result.message ?? 'Check your email.') } catch (error) { setMessage(error instanceof Error ? error.message : 'We could not send another email.') } finally { setBusy(false) } }
  const title = step === 'forgot' ? 'Reset your password' : step === 'reset' ? 'Choose a new password' : step === 'check-email' ? 'Check your inbox' : step === 'verified' ? 'You’re all set' : step === 'error' ? 'We need your attention' : mode === 'join' ? 'Join your neighbourhood' : 'Welcome back'
  return <div className="modal-backdrop" role="dialog" aria-modal="true"><section className="auth-modal"><button className="modal-close" onClick={close}><X/></button><a className="brand"><span className="brand-mark"><MapPin size={20}/></span>Around<span>Me</span></a><h2>{title}</h2>{busy && step === 'form' && <p>Working securely…</p>}{step === 'check-email' ? <><p>{message || 'We sent you an email. Follow the link to continue.'}</p><button className="join wide" disabled={!email || busy} onClick={resend}>Resend verification email</button><button className="link-button" onClick={close}>Close</button></> : step === 'forgot' ? <><p>Enter your email and we’ll send a reset link if an account exists.</p><input type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="Email address"/><button className="join wide" disabled={!email || busy} onClick={submit}>Send reset link</button><button className="link-button" onClick={() => setStep('form')}>Back to sign in</button></> : step === 'reset' ? <><p>Choose a new password with at least 12 characters.</p><input type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="New password"/><button className="join wide" disabled={password.length < 12 || busy} onClick={submit}>Reset password</button></> : step === 'verified' || step === 'error' ? <><p>{message}</p><button className="join wide" onClick={step === 'verified' ? close : () => setStep('form')}>{step === 'verified' ? 'Continue' : 'Try again'}</button></> : <><p>{mode === 'join' ? 'Create your account, then verify your email before joining community conversations.' : 'Sign in to continue to Around Me.'}</p>{mode === 'join' && <input value={name} onChange={e => setName(e.target.value)} placeholder="Your full name"/>}<input type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="Email address"/><input type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Password"/>{mode === 'join' && <label className="privacy-check"><input type="checkbox"/> I agree to the Community Guidelines</label>}<button className="join wide" disabled={busy || !email || password.length < 12 || (mode === 'join' && name.trim().length < 2)} onClick={submit}>{mode === 'join' ? 'Create account' : 'Sign in'}</button>{mode === 'sign in' && <button className="link-button" onClick={() => setStep('forgot')}>Forgot password?</button>}<p className="auth-switch">{mode === 'join' ? 'Already have an account?' : 'New to Around Me?'} <button onClick={() => { onModeChange(mode === 'join' ? 'sign in' : 'join'); setStep('form'); setMessage('') }}>{mode === 'join' ? 'Sign in' : 'Join now'}</button></p></>}</section></div>
}
